ssp_analytics:
  outputs:
    dev:
      dbname: analytics
      host: 172.99.0.2
      pass: d3vP@ss!
      port: 5432
      schema: dev_telqoulaq
      threads: 4
      type: postgres
      user: developer_user
    prod:
      dbname: analytics
      host: 172.99.0.2
      pass: d3vP@ss!
      port: 5432
      schema: public # placeholder
      threads: 4
      type: postgres
      user: developer_user
  target: dev
