name: Daily Refresh (Production)

on:
  schedule:
    - cron: '0 8 * * *' # Runs daily at 8am UTC

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dbt
        run: pip install dbt-postgres

      - name: Install dbt Packages
        run: dbt deps

      - name: Deploy & Test Models (dbt build)
        run: > 
          dbt build -s warehouse marts
          --exclude dim_calendar_dates
          --profiles-dir _project_docs/automation 
          --target prod